
services:
  app:
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: my-express-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
    command: npm start
